import { useState, useEffect } from 'react'
import { invoke } from '@tauri-apps/api/core'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts'
import { useTranslation } from '../i18n'
import Icon from '@mdi/react'
import { mdiRefresh, mdiChartLine, mdiChartBar, mdiTrendingUp, mdiTrendingDown } from '@mdi/js'

export default function Summary () {
  const { t } = useTranslation()
  const [dailySummary, setDailySummary] = useState(null)
  const [yesterdaySummary, setYesterdaySummary] = useState(null)
  const [weeklyStats, setWeeklyStats] = useState([])
  const [monthlyStats, setMonthlyStats] = useState([])
  const [yearlyStats, setYearlyStats] = useState([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState(null)
  const [autoGenerated, setAutoGenerated] = useState(false)

  const today = new Date().toISOString().split('T')[0] // YYYY-MM-DD

  const getYesterday = () => {
    const yesterday = new Date()
    yesterday.setDate(yesterday.getDate() - 1)
    return yesterday.toISOString().split('T')[0]
  }

  const loadDailySummary = async (date = null) => {
    try {
      const summary = await invoke('get_daily_summary', { date })
      return summary
    } catch (err) {
      console.error('Failed to load daily summary:', err)
      return null
    }
  }

  const loadAllData = async () => {
    setLoading(true)
    setError(null)
    try {
      // 加载今天的总结
      const todaySummary = await loadDailySummary(today)
      setDailySummary(todaySummary)

      // 如果今天没有总结且未自动生成过，自动生成
      if (!todaySummary && !autoGenerated) {
        await generateSummary()
        setAutoGenerated(true)
      }

      // 加载昨天的总结（用于对比）
      const yesterdayDate = getYesterday()
      const yesterday = await loadDailySummary(yesterdayDate)
      setYesterdaySummary(yesterday)

      // 加载一周数据（最近7天）
      const weekData = await invoke('get_historical_stats', { days: 7 })
      setWeeklyStats(weekData || [])

      // 加载一月数据（最近30天）
      const monthData = await invoke('get_historical_stats', { days: 30 })
      setMonthlyStats(monthData || [])

      // 加载一年数据（最近365天）
      const yearData = await invoke('get_historical_stats', { days: 365 })
      setYearlyStats(yearData || [])
    } catch (err) {
      console.error('Failed to load summary data:', err)
      setError(err.toString())
    } finally {
      setLoading(false)
    }
  }

  const generateSummary = async () => {
    setGenerating(true)
    setError(null)
    try {
      const summary = await invoke('generate_daily_summary', { date: null })
      setDailySummary(summary)
      // 重新加载所有数据以更新图表
      await loadAllData()
    } catch (err) {
      console.error('Failed to generate daily summary:', err)
      setError(err.toString())
    } finally {
      setGenerating(false)
    }
  }

  useEffect(() => {
    loadAllData()
  }, [])

  // 计算对比数据
  const getComparison = () => {
    if (!dailySummary || !yesterdaySummary) return null

    const screenshotDiff = dailySummary.screenshotCount - yesterdaySummary.screenshotCount
    const summaryDiff = dailySummary.summaryCount - yesterdaySummary.summaryCount
    const durationDiff = dailySummary.totalDurationSeconds - yesterdaySummary.totalDurationSeconds

    return {
      screenshotDiff,
      summaryDiff,
      durationDiff,
      screenshotPercent: yesterdaySummary.screenshotCount > 0
        ? ((screenshotDiff / yesterdaySummary.screenshotCount) * 100).toFixed(1)
        : '0',
      summaryPercent: yesterdaySummary.summaryCount > 0
        ? ((summaryDiff / yesterdaySummary.summaryCount) * 100).toFixed(1)
        : '0',
      durationPercent: yesterdaySummary.totalDurationSeconds > 0
        ? ((durationDiff / yesterdaySummary.totalDurationSeconds) * 100).toFixed(1)
        : '0'
    }
  }

  const comparison = getComparison()

  // 格式化时长
  const formatDuration = (seconds) => {
    const hours = Math.floor(seconds / 3600)
    const minutes = Math.floor((seconds % 3600) / 60)
    if (hours > 0) {
      return `${hours}${t('hours')} ${minutes}${t('minutes')}`
    }
    return `${minutes}${t('minutes')}`
  }

  // 格式化日期
  const formatDate = (dateStr) => {
    const date = new Date(dateStr + 'T00:00:00')
    return date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })
  }

  return (
    <div className='p-6 bg-white min-h-full pb-20'>
      <div className='mb-6 flex items-center justify-between'>
        <div>
          <h2 className='text-2xl font-semibold text-gray-900 mb-1'>{t('summaryTitle')}</h2>
          <p className='text-xs text-gray-500'>{t('summaryDescription')}</p>
        </div>
        <button
          onClick={generateSummary}
          disabled={generating || loading}
          className='px-4 py-2 bg-gray-900 text-white text-sm rounded-lg hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium flex items-center gap-2'
        >
          <Icon path={mdiRefresh} size={1} className={generating ? 'animate-spin' : ''} />
          {generating ? t('generating') : t('generateSummary')}
        </button>
      </div>

      {error && (
        <div className='mb-6 p-4 bg-gray-50 border border-gray-200 rounded-lg text-gray-700'>
          {t('error')}: {error}
        </div>
      )}

      {loading && !dailySummary && (
        <div className='text-center py-12 text-gray-400'>{t('loading')}</div>
      )}

      {!loading && dailySummary && (
        <>
          {/* 今日总结卡片 */}
          <div className='bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-sm'>
            <div className='flex items-center justify-between mb-4'>
              <h3 className='text-lg font-semibold text-gray-900'>
                {new Date(today).toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' })}
              </h3>
              <div className='flex items-center gap-4 text-sm text-gray-600'>
                <span>{dailySummary.screenshotCount} {t('screenshots')}</span>
                <span>{dailySummary.summaryCount} {t('summaries')}</span>
                <span>{formatDuration(dailySummary.totalDurationSeconds)}</span>
              </div>
            </div>

            <div className='prose prose-sm max-w-none prose-gray mb-6'>
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  p: ({ node, ...props }) => <p className='mb-3 text-sm text-gray-700 leading-relaxed' {...props} />,
                  h1: ({ node, ...props }) => <h1 className='text-lg font-semibold text-gray-900 mb-2 mt-4' {...props} />,
                  h2: ({ node, ...props }) => <h2 className='text-base font-semibold text-gray-900 mb-2 mt-3' {...props} />,
                  h3: ({ node, ...props }) => <h3 className='text-sm font-semibold text-gray-900 mb-1 mt-2' {...props} />,
                  ul: ({ node, ...props }) => <ul className='list-disc list-inside mb-2 text-sm text-gray-700 space-y-1' {...props} />,
                  ol: ({ node, ...props }) => <ol className='list-decimal list-inside mb-2 text-sm text-gray-700 space-y-1' {...props} />,
                  li: ({ node, ...props }) => <li className='text-sm text-gray-700' {...props} />,
                  code: ({ node, inline, ...props }) =>
                    inline
                      ? <code className='bg-gray-100 px-1 py-0.5 rounded text-xs text-gray-800 font-mono' {...props} />
                      : <code className='block bg-gray-50 p-2 rounded text-xs text-gray-800 font-mono overflow-x-auto' {...props} />,
                  blockquote: ({ node, ...props }) => <blockquote className='border-l-2 border-gray-300 pl-3 italic text-sm text-gray-600 my-2' {...props} />
                }}
              >
                {dailySummary.content}
              </ReactMarkdown>
            </div>
          </div>

          {/* 与昨天对比 */}
          {comparison && (
            <div className='bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-sm'>
              <h3 className='text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2'>
                <Icon path={mdiChartLine} size={1.2} />
                {t('comparisonWithYesterday')}
              </h3>
              <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
                <div className='bg-gray-50 rounded-lg p-4'>
                  <div className='text-xs text-gray-600 mb-1'>{t('screenshots')}</div>
                  <div className='flex items-center gap-2'>
                    <span className='text-xl font-bold text-gray-900'>{dailySummary.screenshotCount}</span>
                    {comparison.screenshotDiff !== 0 && (
                      <span className={`text-sm flex items-center gap-1 ${comparison.screenshotDiff > 0 ? 'text-green-600' : 'text-red-600'}`}>
                        <Icon path={comparison.screenshotDiff > 0 ? mdiTrendingUp : mdiTrendingDown} size={0.8} />
                        {Math.abs(comparison.screenshotDiff)} ({comparison.screenshotPercent}%)
                      </span>
                    )}
                  </div>
                </div>
                <div className='bg-gray-50 rounded-lg p-4'>
                  <div className='text-xs text-gray-600 mb-1'>{t('summaries')}</div>
                  <div className='flex items-center gap-2'>
                    <span className='text-xl font-bold text-gray-900'>{dailySummary.summaryCount}</span>
                    {comparison.summaryDiff !== 0 && (
                      <span className={`text-sm flex items-center gap-1 ${comparison.summaryDiff > 0 ? 'text-green-600' : 'text-red-600'}`}>
                        <Icon path={comparison.summaryDiff > 0 ? mdiTrendingUp : mdiTrendingDown} size={0.8} />
                        {Math.abs(comparison.summaryDiff)} ({comparison.summaryPercent}%)
                      </span>
                    )}
                  </div>
                </div>
                <div className='bg-gray-50 rounded-lg p-4'>
                  <div className='text-xs text-gray-600 mb-1'>{t('duration')}</div>
                  <div className='flex items-center gap-2'>
                    <span className='text-xl font-bold text-gray-900'>{formatDuration(dailySummary.totalDurationSeconds)}</span>
                    {comparison.durationDiff !== 0 && (
                      <span className={`text-sm flex items-center gap-1 ${comparison.durationDiff > 0 ? 'text-green-600' : 'text-red-600'}`}>
                        <Icon path={comparison.durationDiff > 0 ? mdiTrendingUp : mdiTrendingDown} size={0.8} />
                        {formatDuration(Math.abs(comparison.durationDiff))} ({comparison.durationPercent}%)
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* 一周概况 */}
          {weeklyStats.length > 0 && (
            <div className='bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-sm'>
              <h3 className='text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2'>
                <Icon path={mdiChartBar} size={1.2} />
                {t('weeklyOverview')} (7 {t('days')})
              </h3>
              <ResponsiveContainer width='100%' height={300}>
                <LineChart data={weeklyStats}>
                  <CartesianGrid strokeDasharray='3 3' stroke='#e5e7eb' />
                  <XAxis
                    dataKey='date'
                    tickFormatter={formatDate}
                    stroke='#6b7280'
                    style={{ fontSize: '12px' }}
                  />
                  <YAxis stroke='#6b7280' style={{ fontSize: '12px' }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e5e7eb', borderRadius: '8px' }}
                    labelFormatter={(label) => formatDate(label)}
                  />
                  <Legend />
                  <Line
                    type='monotone'
                    dataKey='screenshotCount'
                    name={t('screenshots')}
                    stroke='#3b82f6'
                    strokeWidth={2}
                    dot={{ r: 4 }}
                  />
                  <Line
                    type='monotone'
                    dataKey='summaryCount'
                    name={t('summaries')}
                    stroke='#10b981'
                    strokeWidth={2}
                    dot={{ r: 4 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          )}

          {/* 月度统计 */}
          {monthlyStats.length > 0 && (
            <div className='bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-sm'>
              <h3 className='text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2'>
                <Icon path={mdiChartBar} size={1.2} />
                {t('monthlyStatistics')} (30 {t('days')})
              </h3>
              <ResponsiveContainer width='100%' height={300}>
                <BarChart data={monthlyStats}>
                  <CartesianGrid strokeDasharray='3 3' stroke='#e5e7eb' />
                  <XAxis
                    dataKey='date'
                    tickFormatter={formatDate}
                    stroke='#6b7280'
                    style={{ fontSize: '11px' }}
                    angle={-45}
                    textAnchor='end'
                    height={80}
                  />
                  <YAxis stroke='#6b7280' style={{ fontSize: '12px' }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e5e7eb', borderRadius: '8px' }}
                    labelFormatter={(label) => formatDate(label)}
                  />
                  <Legend />
                  <Bar dataKey='screenshotCount' name={t('screenshots')} fill='#3b82f6' />
                  <Bar dataKey='summaryCount' name={t('summaries')} fill='#10b981' />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}

          {/* 年度统计 */}
          {yearlyStats.length > 0 && (
            <div className='bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-sm'>
              <h3 className='text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2'>
                <Icon path={mdiChartLine} size={1.2} />
                {t('yearlyStatistics')} (365 {t('days')})
              </h3>
              <ResponsiveContainer width='100%' height={300}>
                <LineChart data={yearlyStats}>
                  <CartesianGrid strokeDasharray='3 3' stroke='#e5e7eb' />
                  <XAxis
                    dataKey='date'
                    tickFormatter={(dateStr) => {
                      const date = new Date(dateStr + 'T00:00:00')
                      return date.toLocaleDateString('zh-CN', { month: 'short' })
                    }}
                    stroke='#6b7280'
                    style={{ fontSize: '11px' }}
                  />
                  <YAxis stroke='#6b7280' style={{ fontSize: '12px' }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e5e7eb', borderRadius: '8px' }}
                    labelFormatter={(label) => formatDate(label)}
                  />
                  <Legend />
                  <Line
                    type='monotone'
                    dataKey='screenshotCount'
                    name={t('screenshots')}
                    stroke='#3b82f6'
                    strokeWidth={2}
                    dot={false}
                  />
                  <Line
                    type='monotone'
                    dataKey='summaryCount'
                    name={t('summaries')}
                    stroke='#10b981'
                    strokeWidth={2}
                    dot={false}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          )}
        </>
      )}

      {!loading && !dailySummary && (
        <div className='text-center py-12'>
          <p className='text-gray-400 mb-4'>{t('noDailySummary')}</p>
          <button
            onClick={generateSummary}
            disabled={generating}
            className='px-4 py-2 bg-gray-900 text-white text-sm rounded-lg hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium'
          >
            {generating ? t('generating') : t('generateSummary')}
          </button>
        </div>
      )}
    </div>
  )
}
